#!/bin/bash
# rmbeast
# Description: Removes files produced by BEAST
# Usage: rmbeast [-f]
# Options: [-f] deletes files without asking (very dangerous!)
# By: Johan Nylander
# 07/11/2008 09:26:23 PM CEST

SOFTWARE="BEAST"
SOFTWAREFILES="*.trees *.log"

if [ -n "$1" ]
    then
    if [ "$1" = "-f" ]
    then
       echo
       rm -rvf $SOFTWAREFILES
       echo
    fi
else
    echo
    echo "Checking for $SOFTWARE output using ls:"
    echo
    FILELIST=`ls $SOFTWAREFILES`
    if [ "$FILELIST" = "" ]
    then
        echo
        echo "Didn't find any $SOFTWARE files"
        echo
    else
        echo
        echo "Found the following output from $SOFTWARE :"
        echo
        for ff in $FILELIST
        do
            echo $ff
        done
        echo
        echo -n "Do you want to delete these files [y/n]? "
        read ANSWER
        if [ "$ANSWER" = "y" ]
        then
            echo
            for ff in $FILELIST
            do
                rm -rvf $ff
            done
        else
            echo
            echo "OK, no files deleted"
        fi
    fi
fi
