#!/bin/bash

# Name: rmphylobayes
# Description: Removes files produced by phylobayes or pbmpi
# Usage: rmphylobayes [-f][-h][-v]
# By: Johan Nylander
# Last modified: tor maj 15, 2025  02:24

SOFTWARE="phylobayes"

SOFTWAREFILES=(
  "*.bplist"
  "*.contdiff"
  "*.modeprofiles"
  "*.param"
  "*.statent"
  "*.trace"
  "*.tree"
  "*.treelist"
)

show_version() {
  echo "0.1"
}

show_help() {
  echo ""
  echo "NAME"
  echo "    rmbayes"
  echo ""
  echo "SYNOPSIS"
  echo "    $0 [-f][-h][-v]"
  echo ""
  echo "DESCRIPTION"
  echo "    Script removes output files from the software $SOFTWARE in the current"
  echo "    working directory. Default (no options) is to be interactive."
  echo ""
  echo "OPTIONS"
  echo "    -f, --force     delete files found without asking"
  echo "    -h, --help      print this help text"
  echo "    -v, --version   print version"
  echo ""
  echo "AUTHOR"
  echo "    Johan Nylander"
  echo ""
  echo "SEE ALSO"
  echo "    <https://github.com/nylander/remove_mcmc_output>"
  echo ""
}

force=0
while :; do
  case $1 in
    -h|-\?|--help)
      show_help
      exit
      ;;
    -v|--version)
      show_version
      exit
      ;;
    -f|--force)
      force=1
      ;;
    -?*)
      printf 'WARN: Unknown option: %s\n' "$1" >&2
      show_help
      exit
      ;;
    *)
      break
  esac
  shift
done

FILELIST=()
for f in "${SOFTWAREFILES[@]}" ; do
  readarray -d '' FF < <(find . -type f -name "$f" -print0)
  if (( ${#FF[@]} )) ; then
    for h in "${FF[@]}" ; do
      FILELIST+=("$h")
    done
  fi
done

if [ ${#FILELIST[@]} -eq 0 ] ; then
  echo ""
  echo "Didn't find any $SOFTWARE files"
  echo "Nothing to be done."
  exit
fi

if [ "$force" = 1 ] ; then
  for ff in "${FILELIST[@]}" ; do
    rm -rvf "$ff"
  done
else
  echo "Found the following output from $SOFTWARE"
  echo ""
  for ff in "${FILELIST[@]}" ; do
    echo "$ff"
  done
  echo ""
  echo -n "Do you want to delete these files [y/n]? "
  read -r ANSWER
  if [ "${ANSWER,,}" = "y" ] ; then
    echo ""
    for ff in "${FILELIST[@]}" ; do
      rm -rvf "$ff"
    done
    echo ""
  elif [ "${ANSWER,,}" = "n" ] ; then
    echo ""
    echo "OK, no files deleted"
    echo ""
  else
    echo ""
    echo "y or n? Not sure ($ANSWER) so exiting."
    echo ""
    show_help
    exit
  fi
fi

